on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Install WiX Toolset
      #   run: |
      #     dotnet tool install --global wix --version 6.0.0
      #     wix --version

      - name: Create wxs file
        shell: bash
        run: |
          python3 tools/windows/msi/create_wxs.py mview6-windows/ mview6.wxs

      - name: Compile WiX Source (.wxs)
        shell: bash
        run: |
          candle -out mview6.wixobj mview6.wxs

      - name: Create MSI Package
        shell: bash
        run: |
          light mview6.wixobj -out mview6.msi

      - name: Upload MSI as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MSI-Installer
          path: |
            mview6.msi
            mview6.wxs

      # - name: Determine current date
      #   id: date
      #   shell: bash
      #   run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # - name: Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     name: ${{ steps.date.outputs.date }}
      #     commit: ${{ github.sha }}
      #     tag: ${{ steps.date.outputs.date }}
      #     body: Windows installer for MView6 (${{ steps.date.outputs.date }})
      #     makeLatest: true
      #     allowUpdates: true
      #     replacesArtifacts: true
      #     artifacts: "mview6.msi, mview6.wxs"
