on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install WiX Toolset
        run: |
          dotnet tool install --global wix --version 6.0.0
          wix --version

      - name: Compile WiX Source (.wxs)
        run: |
          candle -out mview6.wixobj tools\windows\msi\mview6.wxs

      - name: Create MSI Package
        run: |
          light mview6.wixobj -out myinstaller.msi

      - name: Upload MSI as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MSI-Installer
          path: myinstaller.msi
